version: "3"
services:
  web:
    image: bludit/docker:3.10.0
    container_name:  web-app
    ports:
       - "8000:80"
    restart: always
    stdin_open: true
    tty: true


  config:
    build:
        context: .
        dockerfile: Dockerfile_config
    depends_on:
      - web
    container_name: config-app


  nginx-xss:
    build:
      context: .
      dockerfile: Dockerfile_nginx
    container_name: nginx-app
    depends_on:
      - web
    ports:
      - "8222:80"

      
  poc:
    build:
        context: .
        dockerfile: Dockerfile_poc
    depends_on:
      - web
      - config
    container_name: poc-app


  
  bot:
    build:
        context: .
        dockerfile: Dockerfile_botb     
   depends_on:
        - web
        - config
        - nginx-xss
    container_name: bot-app 
  

  ids:
      image: fixel/zeek:latest
      network_mode: service:web
      container_name: zeek
      volumes:
        - ./ids/logs:/usr/local/zeek/logs
        - ./ids/policy_detect_xss:/usr/local/zeek/share/zeek/policy/policy_detect_xss
      command: -C -i eth0 policy/policy_detect_xss